//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackTambourine.Sitecore8.WorkboxPlus.V2.sitecore.shell.Applications.WorkboxPlusV2 {
    
    
    public partial class wbp {
    }
}
